# Generated by Django 5.0.1 on 2024-02-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireHazards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfirehazard',
            name='capture_time',
        ),
    ]
