# Generated by Django 4.2.10 on 2024-02-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireHazards', '0002_remove_userfirehazard_capture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfirehazard',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='fire_hazards_thumbnails/'),
        ),
    ]
