# Generated by Django 4.2.10 on 2024-02-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_spacechecklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacechecklist',
            name='mySpace',
        ),
        migrations.AddField(
            model_name='spacechecklist',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='spaces.spacecategory'),
        ),
    ]
