# Generated by Django 5.0.1 on 2024-01-25 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fireHazards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_type', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('fire_hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_contents', to='fireHazards.firehazard')),
            ],
        ),
    ]
