# Generated by Django 5.0.1 on 2024-02-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduContents', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educontent',
            name='fire_safety_instructions',
            field=models.TextField(),
        ),
    ]
