# Generated by Django 5.0.1 on 2024-02-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduContents', '0004_alter_educontent_fire_safety_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='educontent',
            name='scholarly_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
