# Generated by Django 4.2.10 on 2024-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='fish_score',
            field=models.IntegerField(default=0, verbose_name='Fish Score'),
        ),
    ]
