# Generated by Django 4.2.10 on 2024-02-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_userscore_fish_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(default=' ', verbose_name='문제해설'),
            preserve_default=False,
        ),
    ]
